function plot_Decoding_ANOVAS(decode_fold_label, decode_fold_label_cat,...
    dirs,all_labels,itype,figs_to_run)

% using only 2 figures (figure 6b: big figure and insert) 
% and some anova stats from this 

if ~isfolder([dirs.figdir '/PopulationVectorsCorrelation/' ...
        'Decoding_ANOVAS/'])
    mkdir([dirs.figdir '/PopulationVectorsCorrelation/' ...
        'Decoding_ANOVAS/'])
end
    
if sum(ismember(figs_to_run,0))>0
    for itt = 1:2
        [~,tbl] = anovan(decode_fold_label(...
            decode_fold_label(:,1)==itt,3),...
            decode_fold_label(decode_fold_label(:,1)==itt,4:7),...
            'varnames',{'Trial','Session','Mouse','Rewarded'},...
            'continuous',[1,2],'display','off');  
    
        writecell(tbl,[dirs.figdir ...
            '/PopulationVectorsCorrelation/Decoding_ANOVAS/' ...
            all_labels.typelab{itype} '_Decoding_' ...
            all_labels.ittlabs{itt+1} '_Anovan_table_' all_labels.addon...
            '.txt'],'Delimiter','tab')   
        writecell(tbl,[dirs.figdir ...
            '/PopulationVectorsCorrelation/Decoding_ANOVAS/' ...
            all_labels.typelab{itype} '_Decoding_' ...
            all_labels.ittlabs{itt+1} '_Anovan_table_' all_labels.addon...
            '.xlsx'])    
    end
    
    
    [~,tbl,stats] = anovan(decode_fold_label(decode_fold_label(:,1)>2,3),...
        decode_fold_label(decode_fold_label(:,1)>2,[1 4:7]),'varnames',...
        {'Repeat','Trial','Session','Mouse','Rewarded'},'continuous',[2,3],...
        'display','off');     
    
    writecell(tbl,[dirs.figdir...
        '/PopulationVectorsCorrelation/Decoding_ANOVAS/' ...
        all_labels.typelab{itype} '_Decoding_' all_labels.ittlabs{3+1} ...
        '_Anovan_table_' all_labels.addon '.txt'],'Delimiter','tab')  
    writecell(tbl,[dirs.figdir...
        '/PopulationVectorsCorrelation/Decoding_ANOVAS/' ...
        all_labels.typelab{itype} '_Decoding_' all_labels.ittlabs{3+1} ...
        '_Anovan_table_' all_labels.addon '.xlsx'])    
    
    
    [stats2,mm2] = multcompare(stats,'Dimension',5,'display','off');
    
    figure; hold on; 
    ee = errorbar(1:2,mm2(:,1),mm2(:,2),'o'); 
    ee.Color = 'black'; 
    ee.CapSize = 0; xlim([.5 2.5])
    set(gca,'xtick',1:2,'xticklabel',{'Incorrect';'Correct'}); 
    ylabel('Accuracy (marginal means +- S.E.)')
    title(['Anova P = ' num2str(tbl{6,7})...
        ', Tukey post-hoc: P = ' num2str(stats2(6))])
    helper_saveandclosefig([dirs.figdir '/PopulationVectorsCorrelation/' ...
            'Decoding_ANOVAS/' ...
            all_labels.typelab{itype} '_Decoding_' ...
            all_labels.ittlabs{3+1} '_Anovan_table_' all_labels.addon ...
            '_MultComp_Rewarded'])    
    
    
    
    %rewarded only
    [~,tbl] = anovan(decode_fold_label(decode_fold_label(:,1)>2 & ...
        decode_fold_label(:,7)==1,3),...
        decode_fold_label(decode_fold_label(:,1)>2 & ...
        decode_fold_label(:,7)==1,[1 4:6]),'varnames',...
        {'Repeat','Trial','Session','Mouse'},'continuous',[2,3],...
        'display','off');
    
    writecell(tbl,[dirs.figdir ...
        '/PopulationVectorsCorrelation/Decoding_ANOVAS/' ...
        all_labels.typelab{itype} '_Decoding_' all_labels.ittlabs{3+1} ...
        '_Anovan_table_' all_labels.addon '_rewardedOnly.txt'],'Delimiter','tab') 
    writecell(tbl,[dirs.figdir ...
        '/PopulationVectorsCorrelation/Decoding_ANOVAS/' ...
        all_labels.typelab{itype} '_Decoding_' all_labels.ittlabs{3+1} ...
        '_Anovan_table_' all_labels.addon '_rewardedOnly.xlsx']) 
    
    %incorrect only
    [~,tbl] = anovan(decode_fold_label(decode_fold_label(:,1)>2 & ...
        decode_fold_label(:,7)==0,3),...
        decode_fold_label(decode_fold_label(:,1)>2 & ...
        decode_fold_label(:,7)==0,[1 4:6]),'varnames',...
        {'Repeat','Trial','Session','Mouse'},...
        'continuous',[2,3],'display','off');
    
    writecell(tbl,[dirs.figdir ...
        '/PopulationVectorsCorrelation/Decoding_ANOVAS/' ...
        all_labels.typelab{itype} '_Decoding_' all_labels.ittlabs{3+1} ...
        '_Anovan_table_' all_labels.addon '_incorrectOnly.txt'],'Delimiter','tab')   
    writecell(tbl,[dirs.figdir ...
        '/PopulationVectorsCorrelation/Decoding_ANOVAS/' ...
        all_labels.typelab{itype} '_Decoding_' all_labels.ittlabs{3+1} ...
        '_Anovan_table_' all_labels.addon '_incorrectOnly.xlsx'])    
    
    
     for itt = 1:2
        [~,tbl] = ...
            anovan(decode_fold_label_cat(decode_fold_label_cat(:,1)==itt,3),...
            decode_fold_label_cat(decode_fold_label_cat(:,1)==itt,[4:7]),...
            'varnames',{'Trial','Session','Mouse','Rewarded'},...
            'continuous',[1,2],'display','off');  
    
        writecell(tbl,[dirs.figdir ...
            '/PopulationVectorsCorrelation/Decoding_ANOVAS/' ...
            all_labels.typelab{itype} '_DecodingCat_' ...
            all_labels.ittlabs{itt+1} '_Anovan_table_' all_labels.addon '.txt'],...
            'Delimiter','tab')    
         writecell(tbl,[dirs.figdir ...
            '/PopulationVectorsCorrelation/Decoding_ANOVAS/' ...
            all_labels.typelab{itype} '_DecodingCat_' ...
            all_labels.ittlabs{itt+1} '_Anovan_table_' all_labels.addon '.xlsx'])    
     end
end

if sum(ismember(figs_to_run,[0 6]))>0

    [~,tbl,stats] = ...
        anovan(decode_fold_label_cat(:,3),...
        decode_fold_label_cat(:,[1 4:7]),...
        'varnames',{'TrialType','Trial','Session','Mouse','Rewarded'},...
        'continuous',[2,3],'display','off');
    
    writecell(tbl,[dirs.figdir ...
        '/PopulationVectorsCorrelation/Decoding_ANOVAS/' ...
        all_labels.typelab{itype} '_DecodingCat_' ...
        all_labels.ittlabs{3+1} '_Anovan_table_' all_labels.addon '.txt'],...
        'Delimiter','tab')    
    writecell(tbl,[dirs.figdir ...
        '/PopulationVectorsCorrelation/Decoding_ANOVAS/' ...
        all_labels.typelab{itype} '_DecodingCat_' ...
        all_labels.ittlabs{3+1} '_Anovan_table_' all_labels.addon '.xlsx'])    
    
    
    [stats2,mm2] = multcompare(stats,'Dimension',5,'display','off');
    
    % insert to figure 6b
    figure; hold on; 
    ee = errorbar(1:2,mm2(:,1),mm2(:,2),'o'); 
    ee.Color = 'black'; 
    ee.CapSize = 0; xlim([.5 2.5])
    set(gca,'xtick',1:2,'xticklabel',{'Incorrect';'Correct'}); 
    ylabel('Accuracy (marginal means +- S.E.)')
    title(['Anova P = ' num2str(tbl{6,7})...
        ', Tukey post-hoc: P = ' num2str(stats2(6))])
    
    helper_saveandclosefig([dirs.figdir...
        '/PopulationVectorsCorrelation/Decoding_ANOVAS/' ...
        all_labels.typelab{itype} '_DecodingCat_' all_labels.ittlabs{3+1} ...
        '_Anovan_table_' all_labels.addon '_MultComp_Rewarded'])    

    %get unique sessions per mouse
    [~,~,U] = unique(decode_fold_label_cat(:,5)+...
        (decode_fold_label_cat(:,6)*100));
    %mouse accuracy
    X = splitapply(@mean,decode_fold_label_cat(:,7),U);
    %decoding accuracy
    Y = splitapply(@mean,decode_fold_label_cat(:,2),U);
    [r,p] = corr(X,Y);

    % figure 6b, larger fig
    figure; hold on;
    plot(X,Y,'ok');
    xlabel('Mouse accuracy')
    ylabel('Decoding accuracy')
    title([helper_text_rp(r,p,3) ' n = ' num2str(length(unique(U)))])


    helper_saveandclosefig([dirs.figdir...
        '/PopulationVectorsCorrelation/Decoding_ANOVAS/' ...
        all_labels.typelab{itype} '_DecodingCat_' all_labels.ittlabs{3+1} ...
        '_Anovan_table_' all_labels.addon '_DecodingAccAcrossSessions'])   

end

if sum(ismember(figs_to_run,0))>0
    %rewarded only
    [~,tbl] = anovan(decode_fold_label_cat(decode_fold_label_cat(:,1)>2 ...
        & decode_fold_label_cat(:,7)==1,3),...
        decode_fold_label_cat(decode_fold_label_cat(:,1)>2 & ...
        decode_fold_label_cat(:,7)==1,[1 4:6]),'varnames',...
        {'Repeat','Trial','Session','Mouse'},'continuous',[2,3],...
        'display','off');
    
    writecell(tbl,[dirs.figdir ...
        '/PopulationVectorsCorrelation/Decoding_ANOVAS/' ...
        all_labels.typelab{itype} '_DecodingCat_' all_labels.ittlabs{3+1} ...
        '_Anovan_table_' all_labels.addon '_rewardedOnly.txt'],'Delimiter','tab')    
    writecell(tbl,[dirs.figdir ...
        '/PopulationVectorsCorrelation/Decoding_ANOVAS/' ...
        all_labels.typelab{itype} '_DecodingCat_' all_labels.ittlabs{3+1} ...
        '_Anovan_table_' all_labels.addon '_rewardedOnly.xlsx'])    
    
    %incorrect only
    [~,tbl] = anovan(decode_fold_label_cat(decode_fold_label_cat(:,1)>2 & ...
        decode_fold_label_cat(:,7)==0,3),...
        decode_fold_label_cat(decode_fold_label_cat(:,1)>2 & ...
        decode_fold_label_cat(:,7)==0,[1 4:6]),'varnames',...
        {'Repeat','Trial','Session','Mouse'},'continuous',[2,3],...
        'display','off');
    
    writecell(tbl,[dirs.figdir ...
        '/PopulationVectorsCorrelation/Decoding_ANOVAS/' ...
        all_labels.typelab{itype} '_DecodingCat_' all_labels.ittlabs{3+1} ...
        '_Anovan_table_' all_labels.addon '_incorrectOnly.txt'],'Delimiter','tab')    
    writecell(tbl,[dirs.figdir ...
        '/PopulationVectorsCorrelation/Decoding_ANOVAS/' ...
        all_labels.typelab{itype} '_DecodingCat_' all_labels.ittlabs{3+1} ...
        '_Anovan_table_' all_labels.addon '_incorrectOnly.xlsx'])    
end
